INSERT INTO resources (user_id, category_id, url, title, description, img_url)
VALUES (1, 1, 'https://www.lynda.com/JavaScript-tutorials/Learning-JavaScript-Language/782146-2.html?srchtrk=index%3a2%0alinktypeid%3a2%0aq%3ajavascript%0apage%3a1%0as%3arelevance%0asa%3atrue%0aproducttypeid%3a2', 'Learning the JavaScript Language', 'He shows how to "speak" JavaScript by gaining an understanding of variables, types, objects, arrays, operators, control structures, loops, and functions, through a series of hands-on examples that put these ideas into action.', 'https://cdn.pixabay.com/photo/2015/04/23/17/41/javascript-736400_1280.png');

INSERT INTO resources (user_id, category_id, url, title, description, img_url)
VALUES (2, 2, 'https://www.codecademy.com/learn/learn-ruby', 'Only 10hrs to learn Ruby', 'He shows how to "speak" JavaScript by gaining an understanding of variables, types, objects, arrays, operators, control structures, loops, and functions, through a series of hands-on examples that put these ideas into action.', 'https://cdn.pixabay.com/photo/2016/03/31/18/51/emerald-1294690_1280.png');

INSERT INTO resources (user_id, url, title, description, img_url, category_id) VALUES (1, 'https://mashable.com/shopping/march-21-learn-to-code-python-class-on-sale/', 'Learn how to code with Python during your newfound downtime', 'if you are wondering how you are going to pass your time during this unfortunate quarantine. Why not learn to code with Python', 'https://www.raspberrypi.org/documentation/usage/python/images/python-logo.png', 5);

INSERT INTO resources (user_id, url, title, description, img_url, category_id) VALUES (2, 'https://www.lynda.com/C-tutorials/C-Essential-Training/772322-2.html', 'C++', 'Learn C++', 'https://i.redd.it/31b2ii8hchi31.jpg', 7);

INSERT INTO resources (user_id, url, title, description, img_url, category_id) VALUES (1, 'https://youtu.be/gQojMIhELvM', 'Web Development Tutorial For Beginners', 'Learn Web Dev the way professionals do! This FULL course covers it all.  We will learn HTML, CSS, Javascript and the workspace/computer setup that professionals use.', 'https://freecourseudemy.com/wp-content/uploads/2019/09/Full-Stack-Web-Development-Masterclass-Beginner-To-Advanced.jpg', 1);

INSERT INTO resources (user_id, url, title, description, img_url) VALUES (1,'https://www.lynda.com/JavaScript-tutorials/JavaScript-Essential-Training/574716-2.html', 'JavaScript Essential Training', 'if you are wondering how you are going to pass your time during this unfortunate quarantine. Why not learn to code with Python', 'https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2018/04/CGWd8yk-796x398.jpg')
